// <auto-generated />
namespace FCNDBContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _20191003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191003));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031322594_20191003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
